### ISSUE TITLE
Install using file path instead of ID as Action setting in menu

### ISSUE THREAD

**Issue by sottwell** [modmore/ClientConfig#139]
### Summary
The package installs using the old ID as the Action setting in the Manager's menu.

### Step to reproduce
Install ClientConfig. Go to Menus, and look at its menu item.

### Observed behavior
The Action setting is an ID number.

### Expected behavior
It should be the file path to ClientConfig's action file.
![screen shot 2017-12-28 at 13 30 08](https://user-images.githubusercontent.com/1073780/34414392-c260d130-ebf1-11e7-939d-52d2fd540138.png)

### Environment
ClientConfig version: All
MODX version: All since 2.3 (as per https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/actions-and-menus/action-list)

**Comment by sebastian-marinescu** [comment]
I think I'm running indirectly into this issue. 

If I have two environments (managed via Gitify) and one of them installs the ClientConfig Extra for some reason in a different order than the other one, then I have to fix the QuickStartButtons Button-Link to the ClientConfig-Dashboard on one of the environments (and ignore that further) because the action-ids don't match
– you know what I mean? :smile:

**Comment by Mark-H** [comment]
Fixed in 2.1
