### ISSUE TITLE
Changing the priority of OnHandleRequest breaks Admin-Area.

### ISSUE THREAD

**Issue by jdaehne** [modmore/ClientConfig#165]
### Summary
Changing the Priority of the plugin "ClientConfig" event "OnHandleRequest" shows an error in the Admin-Area instead of the user interface.
ERROR: `Could not find action file at: controllers/default/home.php`

### Step to reproduce
Change the priority to something else than 0 for the plugin "ClientConfig" event "OnHandleRequest".

### Observed behavior
The Admin-Area of ClientConfig shows an error instead of the user interface.

### Expected behavior
Show Admin-Area.

### Environment
- ClientConfig version 2.1.0
- MODX version 2.6.5

![bildschirmfoto 2019-02-28 um 09 42 57](https://user-images.githubusercontent.com/10563227/53553535-32ee4d00-3b3e-11e9-8f3c-99f91a1f811f.png)

![bildschirmfoto 2019-02-28 um 09 40 56](https://user-images.githubusercontent.com/10563227/53553536-32ee4d00-3b3e-11e9-8af4-329abc1b913b.png)

**Comment by Mark-H** [comment]
I can't reproduce this with the provided steps, and the priority only affects in what order plugins, which fire on the same event, are executed. So if changing the priority is breaking something, I suspect it is because of another plugin also firing on OnHandleRequest. 

Right click > update on the event in the plugin's "Events" tab to see what other plugins run.
